name: Build OorBuster

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Build the solution
      run: msbuild OorBuster.sln /p:Configuration=Release

    - name: Upload executable
      uses: actions/upload-artifact@v3
      with:
        name: OorBuster.exe
        path: OorBuster\Release\OorBuster.exe
